<html>
<head>
    <title>Code</title>
    <link rel="stylesheet"
          href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/10.5.0/styles/default.min.css">
    <script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/10.5.0/highlight.min.js"></script>
    <script>hljs.initHighlightingOnLoad();</script>
</head>
<body>
<span id="load_date">${code.date}</span>
<pre id="code_snippet">
            <code class="language-java">
                ${code.code}
            </code>
        </pre>
</body>
</html>